import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // ── Hotel portal palette (Sentinel Green) ──────────────────────────
      colors: {
        // shared surface tokens
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'surface': '#f8f9fa',
        'surface-variant': '#e1e3e4',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'outline': '#717973',
        'outline-variant': '#c1c8c2',
        'on-surface': '#191c1d',
        'on-surface-variant': '#414844',
        'on-background': '#191c1d',
        'background': '#f8f9fa',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        // hotel green
        'h-primary': '#012d1d',
        'h-primary-container': '#1b4332',
        'h-on-primary': '#ffffff',
        'h-on-primary-container': '#86af99',
        'h-secondary': '#555f6d',
        'h-primary-fixed': '#c1ecd4',
        'h-primary-fixed-dim': '#a5d0b9',
        'h-inverse-primary': '#a5d0b9',
        // police blue
        'p-primary': '#1353d8',
        'p-primary-container': '#dbe1ff',
        'p-on-primary': '#f8f7ff',
        'p-on-primary-container': '#0046c3',
        'p-brand-deep': '#1b4332',
        'p-brand-alert': '#dc2626',
        'p-tertiary': '#006e2e',
        'p-tertiary-container': '#82ff99',
        'p-on-tertiary': '#e9ffe6',
        'p-on-tertiary-container': '#006127',
        'p-secondary': '#56606e',
        'p-secondary-container': '#d9e3f4',
        'p-on-secondary-container': '#485260',
        'p-on-surface': '#2b3437',
        'p-on-surface-variant': '#586064',
        'p-on-background': '#2b3437',
        'p-surface-container': '#eaeff1',
        'p-surface-container-low': '#f1f4f6',
        'p-surface-container-highest': '#dbe4e7',
        'p-surface-container-high': '#e3e9ec',
        'p-outline': '#737c7f',
        'p-outline-variant': '#abb3b7',
        'p-error': '#9e3f4e',
        'p-error-container': '#ff8b9a',
        'p-on-error-container': '#782232',
        'p-inverse-primary': '#638aff',
      },
      fontFamily: {
        headline: ['"Public Sans"', 'sans-serif'],
        body: ['"Noto Sans"', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        brand: ['"Noto Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
      },
    },
  },
  plugins: [],
} satisfies Config;
